version: '3'
services:
  proxy:
    build:
      context: ./proxy 
    ports:
      - 80:80  
  covid-back:
    restart: on-failure
    build: 
      context: ./backend
    ports:
      - "5000:5000"     
    container_name: api-server  
  covid-front:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true 
    volumes:
      - ./covidfront:/usr/app/frontend
